name: event_dart
version: 2.0.2
description: Simple, complete and intuitive event emitter written in Dart 
author: Dorian Oszczęda <vxern@wordcollector.co.uk>
homepage: https://github.com/vxern/event_dart
repository: https://github.com/vxern/event_dart
#documentation:
issue_tracker: https://github.com/vxern/event_dart/issues

publish_to: https://pub.dev

environment:
  sdk: '>=2.13.3 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
